import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
export default function Home(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[url,setUrl]=useState(''),[project,setProject]=useState(''),[auth,setAuth]=useState(''),[audits,setAudits]=useState([]),[error,setError]=useState('');
 useEffect(()=>{const t=localStorage.getItem('cta_token');if(t){setToken(t);load(t)}},[]);
 async function load(t=token){if(!t)return;const r=await fetch(API+'/api/audits',{headers:{Authorization:'Bearer '+t}});if(r.ok)setAudits(await r.json());else logout()}
 async function login(e){e.preventDefault();setError('');const r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.detail||'No se pudo iniciar sesión');return}localStorage.setItem('cta_token',d.access_token);setToken(d.access_token);setPassword('');load(d.access_token)}
 function logout(){localStorage.removeItem('cta_token');setToken('');setAudits([])}
 async function run(e){e.preventDefault();if(!url)return;const r=await fetch(API+'/api/audits',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({url,project,authorization_id:auth,scope:['checkout','payment','webhooks']})});if(r.ok){setUrl('');load()}else if(r.status===401)logout()}
 if(!token)return <main style={{fontFamily:'Arial',maxWidth:460,margin:'80px auto',padding:24}}><h1>CiscoTech Payment Auditor</h1><p>Acceso de Superusuario</p><form onSubmit={login} style={{display:'grid',gap:12}}><input type="email" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Iniciar sesión</button></form>{error&&<p style={{color:'crimson'}}>{error}</p>}</main>;
 return <main style={{fontFamily:'Arial',maxWidth:1000,margin:'40px auto',padding:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1>CiscoTech Payment Auditor</h1><p>Sesión de Superusuario</p></div><button onClick={logout}>Cerrar sesión</button></div><form onSubmit={run} style={{display:'grid',gap:12,background:'#f5f5f5',padding:20,borderRadius:12}}><input placeholder="https://cliente.com/checkout" value={url} onChange={e=>setUrl(e.target.value)} required/><input placeholder="Proyecto / cliente" value={project} onChange={e=>setProject(e.target.value)}/><input placeholder="ID de autorización / contrato" value={auth} onChange={e=>setAuth(e.target.value)}/><button>Iniciar auditoría</button></form><h2>Auditorías</h2>{audits.map(a=><div key={a.id} style={{border:'1px solid #ddd',padding:15,margin:'10px 0',borderRadius:8}}><b>{a.request?.project}</b> — {a.status}<br/><small>{a.request?.url}</small>{a.result&&<pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(a.result,null,2)}</pre>}</div>)}</main>
}